# yamllint disable-line rule:document-start
name: Pull Requests & Pushes

# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:

  github-actions:
    name: GitHub Actions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: markdownlint
        uses: reviewdog/action-markdownlint@v0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review

      # - name: pre-commit
      #   uses: pre-commit/action@v2.0.2

      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
        with:
          exclude: "./.git/*"  # Optional.
          fail_on_error: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
          path: "."
          pattern: "*.sh"  # Optional.
          reporter: github-pr-review  # Change reporter.
          shellcheck_flags: '--external-sources --format=gcc --shell=bash'

      - name: yamllint
        uses: karancode/yamllint-github-action@v2.0.0
        with:
          yamllint_config_filepath: '.yamllint.yml'
          yamllint_comment: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
